$(document).ready(function() {
  var myKey = "eoZA48hLZRnyiw9VJEl8o2Wg0UiyTICMTfKvahc0"; //Key generated by api.nasa.gov
  var url = "https://api.nasa.gov/planetary/earth/assets?"
  var begin = "2013-02-11"; //Setting the begin date as the Landsat8 launch date

  $('.preset-menu').change(function() {
    $('#success-mess').html('');
    $('#error-mess').html("");
    
    var selectedPresetOption = $('.preset-menu').find(':selected').text();
    if (selectedPresetOption == "Grand Canyon") {
      $('#long').val('-112.097796');
      $('#lat').val('36.098592');
    } else if (selectedPresetOption == "Niagara Falls") {
      $('#long').val('-79.075891');
      $('#lat').val('43.078154');
    } else if (selectedPresetOption == "Four Corners Monument") {
      $('#long').val('-109.045183');
      $('#lat').val('36.998979');
    } else if (selectedPresetOption == "Medsender HQ") {
      $('#long').val('-74.001472');
      $('#lat').val('40.720583');
    } else if (selectedPresetOption == "Masjid Al-Haram") {
      $('#long').val('39.8579');
      $('#lat').val('21.3891');
    } else if (selectedPresetOption == "") {
      $('#long').val('');
      $('#lat').val('');
    }
  });

  $('#submit').click(function() {
    $('#success-mess').html('');
    $('#error-mess').html("");

    var long = $('#long').val();
    var lat = $('#lat').val();
    flyby(long, lat);
  })

  function flyby(long, lat) {
    var urlAddons = "lon=" + long + "&lat=" + lat + "&begin=" + begin + "&api_key=" + myKey;
    var newURL = url + urlAddons;
    console.log(newURL);

    $.ajax({
      url: newURL,
      success: function(data) {
        //refer to console to the data struct. being analyzed
        console.log('incoming data: ', data);

        if ("error" in data) {
          $('#error-mess').html("Error: " + data.error.toString());
          return;
        } else if (data.count < 2) {
          $('#error-mess').html("Error: Landsat8 has not recieved enough images to make predictions.");
          return;
        } else {
          $('#error-mess').html('');
          var results = data.results;
          var lastResult = results[results.length - 1];
          var lastDate = new Date(lastResult.date);
          var avgTimeDelta = getAvgTimeDelta(results);

          var newDate = new Date(lastDate.toString());
          newDate.setSeconds(lastDate.getSeconds() + avgTimeDelta);

          $('#success-mess').html('According to this data, the predicted date for the next satelitte image at this location is: <br>' + newDate.toString());
        }

      }
    });
  }

});

function getAvgTimeDelta(results) {
  var sum = 0;
  for (var i = 0; i < results.length - 1; i++) {
    var currentDateElement = new Date(results[i].date);
    var nextDateElement = new Date(results[i + 1].date);
    var timeDiff = nextDateElement - currentDateElement;
    sum += timeDiff;

  }
  return sum / ((results.length-1) * 1000);
  //dividing by 1000 changes time units from milliseconds to seconds
}
